spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: foo:com.javaprojref.spring_kafka.multi_method_demo.domain.Foo1,bar:com.javaprojref.spring_kafka.multi_method_demo.domain.Bar1
    consumer:
      bootstrap-servers: localhost:9092
